### ISSUE TITLE
Logging

### ISSUE THREAD

**Issue by ManoharGolleru** [UNC-Project-Open-AAC/OS-DPI#182]
The logging is not working properly now after the recent update(allowing the hot keys to work in OS-DPI),
it is only capturing a minute(less than a minute) worth of usage and all the events that happened before are getting erased and are not logging into the excel file.

**Comment by ManoharGolleru** [comment]
@gbishop  can you please help us with this

**Comment by gbishop** [comment]
Please send an example design so I can try to reproduce the issue.

**Comment by ManoharGolleru** [comment]
Hello Gary,

I am attaching the latest design here

Thank you so much

Best Regards,
Manohar

**Comment by ManoharGolleru** [comment]
I have just emailed you the latest design

**Comment by cdsjeff** [comment]
a related logging issue has to do with the timestamp.   the clock stamp that we have is ok, and we can make it work, but we need to readjust the start time based on the task that the participant is working on. We also want to represent the log in our transcription program Elan and need to sync the start time with our videos.  

It would be helpful if we could elect to have a second.10ths second format.  This is a low-medium importance issue that doesn't need to be solved right now.
J

**Comment by gbishop** [comment]
The issue with seconds is the origin. What does 0 seconds correspond to? We
can easily get seconds since the epoch (Jan 1 1970) but results in huge
numbers...

Obvious origins like "start" are difficult because sessions restart,
browsers get reloaded, etc.

That's why I chose Date + Time. It is unambiguous and survives restarts.

In software we can do anything, we just have to understand the tradeoffs.

**Comment by gbishop** [comment]
Fixed.
