### ISSUE TITLE
Pronounciation

### ISSUE THREAD

**Issue by sofia-bg** [UNC-Project-Open-AAC/OS-DPI#40]
Playing around with speaking pronunciation instead of label. 
Stuck because currently set to speak $Display and once loaded in display I am unsure how to get it to speak #pronounce instead of #label. 
Wondering too how this would work once multiple labels are in the display.

**Comment by gbishop** [comment]
That is an interesting problem. I think you'd do it with another state variable. Let's call it $Pronounce. Anytime a word has a #pronounce field you'd add_word that to $Pronounce, otherwise you'd add #label to it. Then when speaking you'd use $Pronounce instead of $Display. I haven't tried it but I think something like that should work.
